window.productsHotdogs = [
    {
        title: 'Домашний хот-дог',
        price: 290,
        weight: 250,
        calories: 410,
        description: 'Сытный хот-дог с сочной сосиской, свежими овощами, жареным луком и домашним соусом.',
        image: 'img/homemade_hot-dog.jpg',
        ingredients: [
            'Булочка',
            'Сосиска',
            'Огурцы',
            'Помидоры',
            'Жареный лук',
            'Домашний соус',
        ],
        category: 'Хот-доги',
    },
    {
        title: 'Жгучий хот-дог',
        price: 239,
        weight: 245,
        calories: 390,
        description: 'Пикантный хот-дог с жгучим халапеньо для любителей острого.',
        image: 'img/hot-dog1.jpg',
        ingredients: [
            'Булочка',
            'Сосиска',
            'Халапеньо',
            'Кетчуп',
            'Горчица',
        ],
        category: 'Хот-доги',
    },
    {
        title: 'Классический хот-дог',
        price: 220,
        weight: 215,
        calories: 370,
        description: 'Классический хот-дог с сосиской под соусами.',
        image: 'img/classic_hot-dog.jpg',
        ingredients: [
            'Булочка',
            'Сосиска',
            'Кетчуп',
            'Горчица',
        ],
        category: 'Хот-доги',
    },
];
