window.productsSauces = [
    {
        title: 'Сырный соус',
        price: 105,
        weight: 50,
        calories: 120,
        description: 'Нежный сливочный соус с насыщенным сырным вкусом. Отлично подходит к картошке фри и мясу.',
        image: 'img/cheese_sauce.jpg',
        ingredients: [
            'Сыр',
            'Сливки',
            'Соль',
            'Специи',
        ],
        category: 'Соусы',
    },
    {
        title: 'Кисло-сладкий чили',
        price: 105,
        weight: 50,
        calories: 90,
        description: 'Пикантный кисло-сладкий соус с лёгкой остринкой. Идеален для курицы и закусок.',
        image: 'img/chili_sauce.jpg',
        ingredients: [
            'Перец чили',
            'Сахар',
            'Уксус',
            'Томатная паста',
        ],
        category: 'Соусы',
    },
    {
        title: 'Терияки соус',
        price: 105,
        weight: 50,
        calories: 100,
        description: 'Классический японский соус с соевым вкусом и сладкими нотками. Прекрасно сочетается с воком и мясом.',
        image: 'img/teriyaki_sauce.jpg',
        ingredients: [
            'Соевый соус',
            'Сахар',
            'Имбирь',
            'Чеснок',
        ],
        category: 'Соусы',
    },
];
