window.productsPizza = [
    {
        title: 'Мясная',
        price: 1060,
        weight: 700,
        calories: 1200,
        description: 'Пицца с тремя видами мяса, томатным соусом и сыром моцарелла. Для настоящих мясоедов!',
        image: 'img/meat_pizza.jpg',
        ingredients: [
            'Тесто',
            'Томатный соус',
            'Моцарелла',
            'Пепперони',
            'Ветчина',
            'Говядина',
        ],
        category: 'Пицца',
    },
    {
        title: '4 сыра',
        price: 920,
        weight: 650,
        calories: 1100,
        description: 'Классическая пицца с четырьмя видами сыра: моцарелла, дорблю, пармезан и чеддер.',
        image: 'img/cheese_pizza.jpg',
        ingredients: [
            'Тесто',
            'Моцарелла',
            'Дорблю',
            'Пармезан',
            'Чеддер',
        ],
        category: 'Пицца',
    },
    {
        title: 'Пепперони',
        price: 820,
        weight: 600,
        calories: 1050,
        description: 'Пицца с острыми колбасками пепперони, томатным соусом и сыром моцарелла.',
        image: 'img/pepperoni.jpg',
        ingredients: [
            'Тесто',
            'Томатный соус',
            'Моцарелла',
            'Пепперони',
        ],
        category: 'Пицца',
    },
    {
        title: 'Маргарита',
        price: 760,
        weight: 550,
        calories: 900,
        description: 'Лёгкая пицца с томатами, сыром моцарелла и свежим базиликом. Классика итальянской кухни.',
        image: 'img/margarita.jpg',
        ingredients: [
            'Тесто',
            'Томатный соус',
            'Моцарелла',
            'Томаты',
            'Базилик',
        ],
        category: 'Пицца',
    },
];
