# Generated by Django 5.2.4 on 2025-07-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("street", models.CharField(max_length=100)),
                ("house", models.CharField(max_length=10)),
                ("building", models.CharField(blank=True, max_length=10, null=True)),
                ("apartment", models.CharField(blank=True, max_length=10, null=True)),
                ("entrance", models.CharField(blank=True, max_length=10, null=True)),
                ("floor", models.CharField(blank=True, max_length=10, null=True)),
                ("comment", models.TextField(blank=True, null=True)),
                ("total", models.DecimalField(decimal_places=2, max_digits=8)),
                ("delivery", models.DecimalField(decimal_places=2, max_digits=8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
